### ISSUE TITLE
Dolibarr 19.0.0 @ testing branch?

### ISSUE THREAD

**Issue by zunami** [YunoHost-Apps/dolibarr_ynh#114]
hello!

is it possible to add the new version 19.0.0 to the testing branch? i think this is a big version jump 

https://github.com/Dolibarr/dolibarr

**Comment by Crashone** [comment]
It also should be safe to be included in the stable branch, as 19.0.1 is now out.

**Comment by stepcellwolf** [comment]
Any news on this?

**Comment by Crashone** [comment]
No. Btw, 19.0.2 is out https://github.com/Dolibarr/dolibarr/releases/tag/19.0.2

**Comment by Thatoo** [comment]
@ericgaspar could be closed
