### ISSUE TITLE
Dolibarr bug install

### ISSUE THREAD

**Issue by Setsuneh** [YunoHost-Apps/dolibarr_ynh#19]
Hi,

Thank you for your work. Trying installation Dolibarr on Yunohost.

However, I've got this message : 

> L'application a tenté de se mettre à niveau automatiquement, mais les pages d'installation / de mise à niveau ont été désactivées pour des raisons de sécurité (grâce à l'existence d'un fichier de verrouillage install.lock dans le répertoire de documents dolibarr).
> Cliquez sur le lien suivant et si vous atteignez toujours cette page, vous devez supprimer manuellement le fichier install.lock dans le répertoire documents
> Cliquez ici pour aller sur votre application

Yunohost is on a dedicated server (Kimsufi KS-7) with a new installation, Debian Stretch. I've already tried to install with `yunohost app install https://github.com/YunoHost-Apps/dolibarr_ynh/tree/testing --debug`. The issue is the same.

Deleting `install.lock` doesn't work. Re-install this application made the same issue too.

How can I solve it ?

Thanks

**Comment by mastereur** [comment]
Hello,

I have just successfully completed an installation at home with my test server.
During the rework (before July 05, 2019) , I got this message when the configuration file (/var/www/dolibarr/htdocs/conf/conf.php) was not correctly written.
You should check the rights of the installation folder.

**Comment by mastereur** [comment]
Hello,
Did you get a look at the permissions of the folder?

**Comment by mastereur** [comment]
Closing the issue for inactivity

**Comment by amallo** [comment]
Hello,
I have the same problem here avec installing the app, I loop on this message

`
L'application a tenté de se mettre à niveau automatiquement, mais les pages d'installation / de mise à niveau ont été désactivées pour des raisons de sécurité (grâce à l'existence d'un fichier de verrouillage install.lock dans le répertoire de documents dolibarr).
Cliquez sur le lien suivant et si vous atteignez toujours cette page, vous devez supprimer manuellement le fichier install.lock dans le répertoire documents
Cliquez ici pour aller sur votre application
`

I tried to remove install.lock but the message never end

**Comment by Setsuneh** [comment]
Hello,

Try to remove install.lock and Dolibarr folders too. It works normally

**Comment by amallo** [comment]
Thanks @Setsuneh  for your reply, I removed install.lock but same behaviour. What do you mean by Dolibarr folders, I would like to try this

**Comment by amallo** [comment]
I notice that I can log in just just a moment before yunohost finish installation, once it's finished I am always redirected to the install.lock loop

**Comment by amallo** [comment]
Sorry, it was my fault I didn't read carefully the install process, it works like a charm !

**Comment by Cdez** [comment]
What install process? I haven't found any install process?

**Comment by Setsuneh** [comment]
There is not a real process in fact. But a debug if the installation does not like a charm
