### ISSUE TITLE
Hooks are broken

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/dolibarr_ynh#2]
I have a bug "Permission not granted"
Any ideas?

**Comment by labiloute** [comment]
I have forked your project, updated helpers with YNH 2.7, and no issue with the unique hook provided : post_user_create

**Comment by scith** [comment]
Thanks, can you do a pull request once you are done with the changes? This way we can have the improvements in the "yunohost-apps" app
Cheers

**Comment by labiloute** [comment]
Done !

**Comment by mastereur** [comment]
I think that this issue is no longer relevant since the last message and the reworking (after July 05, 2019).

**Comment by mastereur** [comment]
closed due to inactivity
