### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by bleuchtang** [YunoHost-Apps/dolibarr_ynh#21]
On my last upgrade I've seen this error:

./upgrade: line 207: [: -eq: unary operator expected

The problem is here:
https://github.com/YunoHost-Apps/dolibarr_ynh/blob/f8b06e9a578e2d9c62948c46ffe3eca28fc854cf/scripts/upgrade#L207

**Comment by mastereur** [comment]
Hello,

Can you tell me if in the configuration "/etc/yunohost/apps/dolibarr/settings.yml" there is "is_public:'0'" 

If not, did you install the application before the complete rework (before July 05, 2019)?

After the rework, you should have something like this :
```
admin: youraccount
checksum__etc_nginx_conf.d_dolibarr.tld.d_dolibarr.conf: 3e02f309c3d9e8e37b1cbd442b66fe96
checksum__etc_php_7.0_fpm_pool.d_dolibarr.conf: 0ce03253ad4502813567498bbebfdb41
checksum__var_www_dolibarr_htdocs_conf_conf.php: 42fde72a3d3a9615eb490b052989d90a
db_name: dolibarr
domain: dolibarr.tld
final_path: /var/www/dolibarr
fpm_config_dir: /etc/php/7.0/fpm
fpm_service: php7.0-fpm
id: dolibarr
install_time: 1569163384
is_public: '0'
label: Dolibarr
mysqlpwd: XXXXXXX
path: /dolibarr
update_time: 156961581
version: 10.0.2 
```

**Comment by bleuchtang** [comment]
I didn't have is_public: '0' and yes I do the first installation before the complete rework .
