### ISSUE TITLE
out of sort memory

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/dolibarr_ynh#38]
I got a "out of sort memory" in Dolibarr 12, in the invoice module. The same instance worked without problem on Dolibarr 11. Maybe on a smaller database it wouldn't display this.

![image](https://user-images.githubusercontent.com/477243/97441282-d782ec80-1928-11eb-82e7-79e1e6a4f2ad.png)

It doesn't prevent to create a new invoice though. It just prevented a display a "customer invoices drafts" block. The other blocs worked fine.

To fix it, I had to modify

> /etc/mysql/my.cnf

at the line
> sort_buffer_size = 64K

I put 
> sort_buffer_size = 256K

instead. It's a global file, I don't know if it's possible to adjust this setting only for dolibarr.

**Comment by mastereur** [comment]
Indeed, this parameter cannot be modified by the application.
This is a problem of mysql configuration in the system.

The only solution is the one you made.
