### ISSUE TITLE
Check_process is broken

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/dolibarr_ynh#5]
check_process seems to crash when we invoke CURL in the install
Any idea?

**Comment by labiloute** [comment]
Could you explain me a bit how works the check_process ?

**Comment by scith** [comment]
Sure, the git explains it all: https://github.com/YunoHost/package_check
I haven't tested since, bit perhaps the problem solved itself with the updates in packagecheck

**Comment by labiloute** [comment]
I try to pass package_check on my fork, let see what happens

**Comment by labiloute** [comment]
All the lxc step fail, probably cause of my YNH basci install.

Regarding script checks, here is the log:
! [YEP-2.1] "version" field is missing 
! [YEP-1.3] The use of 'free' in license field implies to write something about the license in your README.md 

Upgrade: 
✘ [YEP-2.4] ynh_abort_if_errors is missing. For details,look at https://dev.yunohost.org/issues/419 
Backup :
✘ [YEP-2.4] ynh_abort_if_errors is missing. For details,look at https://dev.yunohost.org/issues/419 
Restore:
✘ [YEP-2.4] ynh_abort_if_errors is missing. For details,look at https://dev.yunohost.org/issues/419

**Comment by mastereur** [comment]
I think that this issue is no longer relevant since the last message and the reworking (after July 05, 2019).

**Comment by mastereur** [comment]
closed due to inactivity
