### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by EpicTGuy** [YunoHost-Apps/dolibarr_ynh#55]
Hello !

I want to know if there is a mobile interface for dolibarr ?
If not, can you make something ?
Actually I can't go to dolibarr on my phone with yunohost.

Thanks

**Comment by gmilad** [comment]
(English below)
Bonsoir,

Concernant les fonctionnalités propres à l'application Dolibarr je vous encourage à directement les poser sur le GitHub de Dolibarr accessible à cette adresse :

https://github.com/Dolibarr/dolibarr

Pour répondre à votre question voici le lien vers une application mobile pour Dolibarr :

https://www.dolistore.com/fr/outils-externes-et-appli-mobiles/365-DoliDroid-pour-Dolibarr.html

Il faut également savoir qu'au fur et à mesure des nouvelles versions le point sur l'affichage sur les mobiles et tablettes et de plus en plus amélioré, d'ailleurs la version 14 qui est en cours de développement apporte de nouvelles choses.

Cordialement,
Gaëtan.

(English)
Good evening,

Concerning Dolibarr application specific features, I encourage you to ask them directly on the Dolibarr GitHub accessible at this address :

https://github.com/Dolibarr/dolibarr

To answer your question here is the link to a mobile application for Dolibarr :

https://www.dolistore.com/en/external-tools-and-mobile-apps/365-DoliDroid-for-Dolibarr.html

You should also know that with each new version the point on display on mobiles and tablets is more and more improved, moreover the version 14 which is under development brings new things.

Sincerely,
Gaëtan.
