### ISSUE TITLE
Fresh install can't set settings

### ISSUE THREAD

**Issue by GuillermoAnkh** [YunoHost-Apps/dolibarr_ynh#59]
Hi, i don't know how to passe out this bug.
Sorry i don't have the habbit to repport bug and if you need some more information please tell me
Thanks a lot

### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: * Old laptop or computer*
- YunoHost version: 4.2.6.1
- I have access to my server: *All the way*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: classical with the store apps.

### Steps to reproduce

1. Going to the app store.
2. Installing the app.
3. Trying to do the fist step and select French land then bug.

### Logs

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210710151925
Dolibarr: 13.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.29-1+0~20210701.86+debian10~1.gbp7ad6eb
Serveur: nginx/1.14.2
OS: Linux ankh.gr 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

Url sollicitée: /dolibarr/admin/company.php
Referer: https://ankh.gr/dolibarr/admin/company.php?mainmenu=home&action=edit
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, ldap
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid as id, d.code_departement as code, d.nom as name, d.active, c.label as country, c.code as country_code, r.code_region as region_code, r.nom as region_name FROM llx_c_departements as d, llx_c_regions as r,llx_c_country as c WHERE d.fk_region=r.code_region and r.fk_pays=c.rowid and d.rowid= AND d.active = 1 AND r.active = 1 AND c.active = 1 ORDER BY c.code, d.code_departement
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND d.active = 1 AND r.active = 1 AND c.active = 1 ORDER BY c.code, d.code_de...' at line 1

**Comment by mastereur** [comment]
Because of this error in the database charset, older V13 installations have a database gap.

If possible, the old application should be uninstalled and then reinstalled in order to have a consistent database.
