### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/dolibarr_ynh#66]
### Describe the bug

Après l'installation de l'app dolibarr, j'ai une première erreur due au fichier install.lock.
Après suppression en ligne de commande de ce fichier, à la première connexion on tombe sur une page qui demande si on est sur une mise à jour ou première installation. J'ai choisi première installation, et en suivant les étapes j'obtiens cette erreur : 

<html><body>

Création des clés étrangères et des index pour la table llx_const.key Request 579 : ALTER TABLE llx_const ADD UNIQUE INDEX uk_const (name, entity) | Erreur SQL DB_ERROR_RECORD_ALREADY_EXISTS Duplicate entry 'LDAP_FILTER_CONNECTION-1' for key 'uk_const'
-- | --

</body>
</html>

Ensuite, à l'étape suivante, il demande un mot de passe pour le compte qu'on avait défini comme administrateur au moment de l'installation, puis j'ai l'erreur suivante : 

```
Echec de la création du compte administrateur Dolibarr L'identifiant totom existe déjà.


Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20211008164037
Dolibarr: 14.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.31-1+0~20210923.88+debian10~1.gbpac4058
Serveur: nginx/1.14.2
OS: Linux lamo 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

Url sollicitée: /install/step5.php
Referer: https://jolibar.lapoursuite.fr/install/step4.php
Gestionnaire de menu:

Modules/Applications: user, ldap
Message: step5.php: unknown choice of action
```

Évidemment l'utilisateur existe déjà, vu qu'on l'a choisi parmis les utilisateurs yunohost. Est-ce que c'est normal de passer par ce setup à l'installation ? J'ai aussi essayé le choix suggéré, "mise à jour 13.0 ou 14.0.0-»14.0", ça a l'air de bien marcher, mais à la fin quand je veux accéder à l'application, je retombe sur la page "Installation ou mise à jour de dolibarr".

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH and through the webadmin and direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: I have installed and then removed dolibarr last year on this server, don't know if something can interfere.
- Using, or trying to install package version/branch: 14.0.2~ynh1

**Comment by tomdereub** [comment]
Non, ça n'a pas l'air d'y ressembler, moi je n'ai aucun problème à l'installation, j'arrive même à accéder et utiliser Dolibarr normalement juste après l'installation, et à un moment ça bascule sur la page de mise à jour et ça reste bloqué dessus.
J'ai trouvé ça dans les logs dans /var/log/dolibarr/install4.html : https://plaf.fr/zerobin/?cac3b6bd4c39aca0#4ggJ1kFcByNsDmnPpmpeHrqRYyC4QM5w4kwkW4iYBTvY
Je ne sais pas si ça peut aider...

**Comment by mastereur** [comment]
Désolé du temps de réponse.

Rien d'anormal dans le log. Je ne vois pas du tout d'où ça provient.
Est-il possible de faire le test d'installation sur un autre PC ?

**Comment by tomdereub** [comment]
J'ai essayé hier sur un autre serveur, et ça a l'air de marcher normalement.
Est-ce que tu aurais d'autres pistes pour essayer de débloquer ça sur le premier serveur ? Je peux réessayer à nouveau de désinstaller complètement, est-ce que tu saurais où il pourrait rester des traces de Dolibarr à effacer à la main ?

**Comment by mastereur** [comment]
Je n'ai pas d'autres pistes, je sèche complètement sur ce problème. :(

Les seules infos externes sont la BDD, dans /var/log/dolibarr ou bien dans /documents/dolibarr.log mais ils sont supprimés après désinstallation.
