### ISSUE TITLE
Dolibarr install fail - ERROR 1146 (42S02) at line 1: Table 'dolibarr.llx_const' doesn't exist

### ISSUE THREAD

**Issue by jn-powerlan** [YunoHost-Apps/dolibarr_ynh#76]
### Dolibarr install failed - ERROR 1146 (42S02) at line 1: Table 'dolibarr.llx_const' doesn't exist

When i try to install dolibarr on fresh yuno install it fail from cmdline or from webadmin.

### Context

- Hardware: debian 11 VM on proxmox
- YunoHost version: 11.0.4
- I have access to my server: *Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: 14.0.5~ynh1

### Steps to reproduce

- sudo yunohost app install dolibarr

### Expected behavior

dollibarr successful installation

### Logs

https://paste.yunohost.org/raw/vitawadepi

**Comment by mastereur** [comment]
Hello,

It seems that your problem is the same as #65 where it was a problem with the writing speed on the disk.

Have you tried an installation on another virtualization system or PC to see if that solves the problem.

**Comment by jn-powerlan** [comment]
When i use the testing branch the problem disappears, so it's not a speed disk issue.

**Comment by mastereur** [comment]
Hello,

Thank you for your feedback.
With the debug mode you don't have the problem, maybe the fact to have more details slows down the installation process.

I will make a test version by adding a sleep between each call to the Dolibarr installation system.

**Comment by mastereur** [comment]
Hello,

I have just updated the installation script.
Is it possible to make a new installation with
`sudo yunohost app install https://github.com/mastereur/dolibarr_ynh/tree/testing`

On my side the new script works but as I don't have your problem, it is impossible for me to check if it changes something.

**Comment by mastereur** [comment]
Hello,

Have you tried the installation as described in my previous comment?

Thank you in advance for your feedback.

**Comment by jn-powerlan** [comment]
Hello,
After a fresh debian11 install and yunohost 11.0.5, the problem completely disappear. (on stable and testing branch of dolibarr_ynh)
Probably something in yunohost 11.0.5 fix the problem.
