### ISSUE TITLE
I think something needs to be deleted but I'm too stupid to figure out how and so the app fails

### ISSUE THREAD

**Issue by baboonandsloth** [YunoHost-Apps/dolibarr_ynh#77]
sorry for the lack of details, just starting out. The install looks like it works but when I try to go into the site I always get:

The application tried to self-upgrade, but the install/upgrade pages have been disabled for security (by the existence of a lock file install.lock in the dolibarr documents directory).
If an upgrade is in progress, please wait. If not, click on the following link. If you always see this same page, you must remove/rename the file install.lock in the documents directory.
[Click here to go to your application](https://baboonandsloth.com/dolibarr/admin/index.php?mainmenu=home&leftmenu=setup)

Now, I don't know how to delete this so it's a dead/failed app for me :(

**Comment by mastereur** [comment]
Hello,

Without any feedback on a potential test from you, I close the ticket
