### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by hzm170** [YunoHost-Apps/dolibarr_ynh#84]
### Describe the bug

*When you logout, it gives you error saying "Applicative disconnection should be useless when connection was made in mode http" even tho the HTTP is now HTTPS...

### Context

- Hardware: *ARM64 board / OCI / ...*
[YunoHost](https://yunohost.org/) 11.0.9.8 (stable).
- I have access to my server: *SSH/ ROOT | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

The script name is: Dolibarr

### Steps to reproduce

-Ah, Noting was done, just install and that's all,, but when u logout noting happens

**Comment by mastereur** [comment]
Hello,

This is a normal limitation due to the fact that the connection is made through Yunohost SSO.

To disconnect you have to go to the small logo (bottom right) Yunohost and disconnect.
