### ISSUE TITLE
It works

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/dolibarr_ynh#9]
Salut,

Je viens d'essayer ton package pour YunoHost 2.7.9.
Tout semble fonctionner. Nous sommes un réseau d'associations très intéressé par ton package, y-a-t-il des tests que nous pourrions mener qui pourraient aider ?

bonne journée

**Comment by yolateng0** [comment]
salut
une fresh install a également fonctionné pour moi. Néanmoins 2 upgrades ont ete nécessaire pour parvenir à la version stable 7.0.1.

**Comment by mastereur** [comment]
I think that this issue is no longer relevant since the last message and the reworking (after July 05, 2019).

**Comment by mastereur** [comment]
closed due to inactivity
