### ISSUE TITLE
WARNING - 688  Source path '/etc/php/8.0/fpm/pool.d/dolibarr.conf' does not exist

### ISSUE THREAD

**Issue by zunami** [YunoHost-Apps/dolibarr_ynh#91]
i have a problem with upgrading from 15.0.3 to 16.0.3

WARNING - 688  Source path '/etc/php/8.0/fpm/pool.d/dolibarr.conf' does not exist

I have no idea what it has there and how I can fix the error

> 2022-12-09 11:10:59,959: DEBUG - 639  ++ app=dolibarr
> 2022-12-09 11:10:59,959: DEBUG - 639  ++ [[ do_not_backup_data =~ (unprotected|protected|skipped)_ ]]
> 2022-12-09 11:10:59,959: DEBUG - 640  ++ ynh_app_setting get dolibarr do_not_backup_data
> 2022-12-09 11:10:59,999: DEBUG - 680  + do_not_backup_data=
> 2022-12-09 11:10:59,999: DEBUG - 680  + '[' '!' -e /etc/php/8.0/fpm/pool.d/dolibarr.conf ']'
> 2022-12-09 11:11:00,000: DEBUG - 680  + ynh_print_warn '--message=Source path '\''/etc/php/8.0/fpm/pool.d/dolibarr.conf'\'' does not exist'
> 2022-12-09 11:11:00,006: DEBUG - 687  + ynh_print_log 'Source path '\''/etc/php/8.0/fpm/pool.d/dolibarr.conf'\'' does not exist'
> 2022-12-09 11:11:00,006: DEBUG - 687  + echo -e 'Source path '\''/etc/php/8.0/fpm/pool.d/dolibarr.conf'\'' does not exist'
> 2022-12-09 11:11:00,006: DEBUG - 687  + '[' 0 == 0 ']'
> 2022-12-09 11:11:00,007: WARNING - 688  Source path '/etc/php/8.0/fpm/pool.d/dolibarr.conf' does not exist
> 2022-12-09 11:11:00,007: DEBUG - 688  + echo /etc/php/8.0/fpm/pool.d/dolibarr.conf
> 2022-12-09 11:11:00,007: DEBUG - 688  + grep --quiet /etc/fail2ban
> 2022-12-09 11:11:00,008: DEBUG - 688  + return 1
> 2022-12-09 11:11:00,008: DEBUG - 688  + ynh_exit_properly
> 2022-12-09 11:11:00,510: DEBUG - 1191 + exit 1
> 2022-12-09 11:11:01,511: DEBUG - 2192 Could not run script: /var/cache/yunohost/app_tmp_work_dirs/app_1ug0ikxm/scripts/backup
> 2022-12-09 11:11:01,513: WARNING - 2194 Could not back up dolibarr
> 2022-12-09 11:11:01,516: DEBUG - 2197 The operation 'Create a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20221209-111059-backup_create' to get help
> 2022-12-09 11:11:01,521: DEBUG - 2202 action [1346618.1] executed in 2.097s
> 2022-12-09 11:11:01,521: WARNING - 2202 Nothing to save
> 2022-12-09 11:11:01,543: DEBUG - + ynh_die '--message=Backup failed, the upgrade process was aborted.'
> 2022-12-09 11:11:01,554: WARNING - Backup failed, the upgrade process was aborted.
> 2022-12-09 11:11:02,556: ERROR - dolibarr konnte nicht aktualisiert werden: Es ist ein Fehler im App-Upgrade-Skript aufgetreten

[2022-12-09.txt](https://github.com/YunoHost-Apps/dolibarr_ynh/files/10194205/2022-12-09.txt)

**Comment by mastereur** [comment]
Hello,
It's strange that the update asks to delete a configuration in php8.0 when the requested version is 7.4.

Can you give me the return of the command :
Sudo echo $(yunohost app setting dolibarr phpversion)

Thanks

**Comment by zunami** [comment]
```
root@yunohost:~# echo $(yunohost app setting dolibarr phpversion)
8.0
```

**Comment by zunami** [comment]
I have solved the problem with

```
sudo yunohost app setting dolibarr phpversion -v "7.4"
sudo yunohost app upgrade dolibarr -F
```
after that i could do the update

**question can you upgrade dolibarr 16.0.3 already to php 8.0? in beta 17 it is already minimum requirement???
reason: cdav has minimum requirement php 8.0**

**Comment by mastereur** [comment]
Hello,

Good news! This is exactly what I was going to tell you to do?

I was going to ask you to check if there was a dolibarr.conf file in etc/php/8.0/fpm/, etc/php/7.4/fpm, etc.

Then update the information with the command. `sudo yunohost app setting dolibarr phpversion -v "7.4"`

I was thinking to put the version 8.0 but unfortunately according to the official site : 
https://wiki.dolibarr.org/index.php?title=Versions

> Dolibarr works on PHP 8.0 and 8.1 but many warnings will be generated in the web server logs. The removal of these warnings is planned for version 17.

**Comment by zunami** [comment]
thanks then i guess i have to wait for version 17 until cdav works

[Befox/cdav](https://github.com/Befox/cdav)

**Comment by mastereur** [comment]
Yes, we'll have to be patient.
