### ISSUE TITLE
Unable to connect after first installation

### ISSUE THREAD

**Issue by Bargin17** [YunoHost-Apps/dolibarr_ynh#92]
Hi, I've tried to install many times Dolibarr, but I always have the same bug after the installation. 

--- 

### 
First : I need to remove install.lock
Then : I can launch the first installation
At the end, it asks a password for the first user (I can't choose the login btw). 
Then I arrive at the login page, and I can't connect, with a wrong password or login advertisement ......

### Context

- Hardware: Yunohost on a Synology VM
- YunoHost version: 11.0.10.2 (stable)
- Dollibarr version : 16.0.3

**Comment by mastereur** [comment]
Issue closed after 3 weeks of waiting for a response
