### ISSUE TITLE
After Upgrade from 16.0.4 to 16.0.5 is a Bug

### ISSUE THREAD

**Issue by zunami** [YunoHost-Apps/dolibarr_ynh#97]
After Upgrade from 16.0.4 to 16.0.5 is a Bug

DolibarrHasDetectedError.
InformationToHelpDiagnose:
Date: 20230402131101
Dolibarr: 16.0.5 - https://www.dolibarr.org
PHP: 7.4.33
Server: nginx/1.18.0
OS: Linux yunohost 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

RequestedUrl: /dolibarr/
Referer: https://domain.com/yunohost/sso/?r=aHR0cHts6Ly9yZWJsZXIubmFDFSxvbGliYXJyLw==
MenuManager:

DatabaseTypeManager: mysqli
RequestLastAccessInError: ErrorNoRequestInError
ReturnCodeLastAccessInError: ErrorNoRequestInError
InformationLastAccessInError: ErrorNoRequestInError

Message: host=localhost, port=3306, user=dolibarr, databasename=dolibarr, Connection refused

**Comment by mastereur** [comment]
Hello,

Did you check if going back to the version 16.0.4 backup fixes the problem?

You should have a backup on "[domain]/yunohost/admin/#/backup/local/info/dolibarr-pre-upgrade2" with "Version 16.0.4~ynh1" inside.

To go back to this version, you have to delete the application from the Yunohost management, then restore the backup (remember to download the backup on another device)

According to the line `Message: host=localhost, port=3306, user=dolibarr, databasename=dolibarr, Connection refused` it seems that it comes from a database error.

Waiting for your return

**Comment by zunami** [comment]
yes, the backup is
/home/yunohost.backup/archives/dolibarr-pre-upgrade1.tar
Dolibarr version 16.0.4~ynh1

when I try to restore it the next error comes up

```
2023-04-04 14:18:18,583: DEBUG - + ynh_app_setting set dolibarr mysqlpwd **********
2023-04-04 14:18:18,630: DEBUG - + ynh_mysql_connect_as --user=dolibarr --password=********** --database=dolibarr
2023-04-04 14:18:18,683: DEBUG - + database=dolibarr
2023-04-04 14:18:18,683: DE
[20230404-141803.txt](https://github.com/YunoHost-Apps/dolibarr_ynh/files/11149608/20230404-141803.txt)
BUG - + mysql --user=dolibarr --password=********** --batch dolibarr
2023-04-04 14:18:20,339: WARNING - ERROR 1062 (23000) at line 4528: Duplicate entry 'PRODUCT_CODEPRODUCT_ADDON-1' for key 'uk_const'.
```

**Comment by mastereur** [comment]
Hello,

This error indicates that a data in the database is not correct and was already present before the update.

To correct this, you have to download the backup, modify the database file (dolibarr-pre-upgrade2\apps\dolibarr\backup\db.sql) by deleting the duplicate data, then put back the modified backup and finally restore by Yunohost.

Don't forget to backup your backup

**Comment by zunami** [comment]
I do not quite understand

you want me to delete "db.sql"? 

or delete an entry from the "db.sql"?
because if it is an entry I will not be able to do that because I do not know anything about databases

**Comment by mastereur** [comment]
Hello,

We need to modify the db.sql file.
You have to find the duplicate value PRODUCT_CODEPRODUCT_ADDON and delete it

The line should look like 
`insert into uk_const values 'PRODUCT_CODEPRODUCT_ADDON-1'`

**Comment by zunami** [comment]
thank you very much has helped
